let datos = [
    {
        "pregunta" : "¿Qué es un calzado de seguridad?",
        "respuesta" : "En Argentina, se denomina calzado de seguridad a aquel calzado que cuenta con una certificación otorgada por un organismo reconocido.<br>La norma más reconocida y aceptada en Argentina, por cubrir amplios aspectos de los riesgos en los pies de los trabajadores, es la norma 3610 de IRAM.<br>Esta norma, además de describir las distintas tipologías de calzado, adecuadas para distintos ámbitos de trabajo, describen las condiciones obligatorias que estos calzados deben cumplir para ser considerados calzado de seguridad.<br>Entre estas condiciones figuran poseer una puntera de seguridad certificada, determinada proporción de los materiales constitutivos de la capellada y el espesor mínimo que deben tener las suelas. Establece además una serie de ensayos obligatorios, muchos de los cuales se basan en otras normas de certificación.<br>La aprobación de estos ensayos permite el uso del sello de conformidad Norma 3610 de IRAM."
    },

    {
        "pregunta" : "¿Cómo elijo el calzado adecuado?",
        "respuesta" : "El calzado debe resultar cómodo, sin opresión del pie del usuario.<br>Esta condición se da en aquellos calzados fabricados con hormas amplias y puntas redondeadas como son las hormas utilizadas para fabricar los calzados Borcal.<br>La puntera de protección, certificada bajo norma IRAM 3643 e imprescindible para que un calzado sea llamado calzado de seguridad, debe acompañar esta amplitud del calce y permitir el alojamiento cómodo de los dedos, de nada serviría una horma amplia con una puntera de protección angosta.<br>El calzado debe mostrar adaptación eficiente a los movimientos del pie, de forma que no entorpezca su movimiento y a la vez, brinde la protección buscada. Por ello, las suelas con tapones pronunciados y ranuras son muy adecuadas ya que ofrecen flexibilidad y a la vez, el agarre necesario para evitar resbalones y/o caídas.<br>El material de capellada debe brindar protección térmica con capacidad transpirable, esto es, permitir la evaporación de la humedad del pie en ambientes cálidos.<br>La plantilla de confort debe ser blanda y con cierto espesor, lavable, preferiblemente, con algún tipo de tratamiento antimicótico.<br>En otras palabras, un calzado confortable debe ser ligero, flexible y estable, con una suela resistente al desgaste y confortable al uso y a las flexiones del pie, especialmente en su articulación, cualidades estas encontradas en los calzados Borcal."
    },

    {
        "pregunta" : "¿Qué es la Norma IRAM 3610?",
        "respuesta" : "Ya hemos mencionado que los calzados Borcal están certificado bajo norma IRAM 3610, ahora bien, ¿qué es y de qué trata esta norma?<br>Una norma de certificación es, generalmente, un compendio de normas y ensayos que enmarca las certificaciones.<br>La norma IRAM 3610 comprende varias decenas de normas y ensayos, que dan marco al instituto verificador, en este caso el IRAM (Instituto Argentino de Normalización y Certificación, originalmente Instituto de Racionalización Argentino de Materiales), para que el mismo, otorgue su certificado, cuando el calzado estudiado, alcance los estándares fijados.<br>Hay ensayos como el de resistencia al impacto, resistencia a la compresión, o resistencia al despegue de la suela, que se efectúan con el calzado terminado, y otros, como resistencia al desgarro o a la fricción, que se efectúan a los componentes del calzado, ya sea en su capellada, en el forro, en las lengüetas u otras partes del calzado.<br>Por otra parte, establece los requisitos para una certificación general básica y para certificaciones opcionales como la condición dieléctrica o la condición antiperforante.<br>En al caso de las punteras de acero, por ejemplo, deben ser certificadas antes por otra norma, la IRAM 3643, y luego pasar el ensayo de impacto y compresión, en el producto terminado.<br>En apariencia sería un doble ensayo, pero lo cierto es que el desempeño de la puntera de acero en la protección de los dedos del pie, depende en gran medida, de la suela del calzado.<br>La norma IRAM 3610 está en revisión permanente y año tras año, una comisión técnica de IRAM, estudia las modificaciones que se hacen a nivel mundial en normas europeas y norteamericanas, con el fin de incluirlas, previos estudios de factibilidad, en la última versión publicada.<br>Estas modificaciones se someten a discusión pública antes de ser incluidas y una vez que obtienen el consenso de todos los actores involucrados, consumidores, fabricantes, proveedores de materias primas, institutos certificadores y de inspección y estamentos gubernamentales, se incluyen en la nueva versión de la norma a ser publicada.<br>Por este motivo, cuando se revisa una certificación de un calzado, es importante verificar que la misma se haya hecho sobre la última actualización.<br>Así, se puede estar seguro que el producto ha sido ensayado y verificado, según los últimos estándares que las industrias exigen para el cuidado de sus trabajadores.<br>"
    }
]